services:

  mysql:
    image: mysql:8.0  # 使用 MySQL 8.0 镜像
    container_name: GinAdmin  # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 root 用户的密码
      MYSQL_DATABASE: data  # 创建初始数据库
      MYSQL_USER: admin123  # 创建初始用户
      MYSQL_PASSWORD: qwertyu  # 设置初始用户的密码
    ports:
      - "3306:3306"  # 将主机的 3306 端口映射到容器的 3306 端口
    volumes:
      - ./mysql_data:/var/lib/mysql  # 数据持久化，将容器中的 MySQL 数据目录挂载到主机的 ./mysql_data 目录
    restart: unless-stopped  # 容器停止时自动重启
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    privileged: true
    volumes:
      - ./.redis/data:/data
      - ./.conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.redis/logs:/logs
    command: ["redis-server"]
    ports:
      - 6379:6379
